# This is the annotated source code for [Pow](http://pow.cx/), a
# zero-configuration Rack server for Mac OS X. See the [user's
# manual](http://pow.cx/manual.html) for information on installation
# and usage.
#
# The annotated source HTML is generated by
# [Docco](http://jashkenas.github.com/docco/).

# ## Table of contents
module.exports =

  # The [Configuration] class stores settings for
  # a Power daemon and is responsible for mapping hostnames to Rack
  # applications.
  Configuration:   require "./configuration"

  # The [Daemon] class represents a running Pow daemon.
  Daemon:          require "./daemon"

  # [DnsServer] handles incoming DNS queries.
  DnsServer:       require "./dns_server"

  # [HttpServer] handles incoming HTTP requests.
  HttpServer:      require "./http_server"

  # [Installer] compiles and installs local and system
  # configuration files.
  Installer:       require "./installer"

  # [Logger] instances keep track of everything that
  # happens during a Power daemon's lifecycle.
  Logger:          require "./logger"

  # The [util] module contains various helper functions.
  util:            require "./util"
